version: "3.4"
services:
  neko:
    build: .
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./bin/home/neko:/home/neko:rw
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    privileged: true
    environment:
      NEKO_SCREEN: 1280x720@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
      NEKO_BROADCAST_URL: rtmp://ome.thuan.au:1935/app/stream-neko
      NEKO_NAT1TO1: 192.168.0.34
      NEKO_HWENC: NVENC
      NEKO_VIDEO_CODEC: h264
